-- Désactiver temporairement les contraintes de clé étrangère
SET session_replication_role = 'replica';

-- Réinitialiser les données des tables secondaires (relations N-N et détails)
TRUNCATE TABLE produit_symptome RESTART IDENTITY CASCADE;
TRUNCATE TABLE produit_substance RESTART IDENTITY CASCADE;
TRUNCATE TABLE produit_genre RESTART IDENTITY CASCADE;
TRUNCATE TABLE produit_trancheage RESTART IDENTITY CASCADE;
TRUNCATE TABLE contre_indication RESTART IDENTITY CASCADE;
TRUNCATE TABLE maladie_symptome RESTART IDENTITY CASCADE;
TRUNCATE TABLE substance_symptome RESTART IDENTITY CASCADE;
TRUNCATE TABLE agent_substance RESTART IDENTITY CASCADE;

TRUNCATE TABLE vente_details RESTART IDENTITY CASCADE;
TRUNCATE TABLE achat_details RESTART IDENTITY CASCADE;
TRUNCATE TABLE mouvement_stock_details RESTART IDENTITY CASCADE;

-- Réinitialiser les tables principales
TRUNCATE TABLE vente RESTART IDENTITY CASCADE;
TRUNCATE TABLE achat RESTART IDENTITY CASCADE;
TRUNCATE TABLE mouvement_stock RESTART IDENTITY CASCADE;
TRUNCATE TABLE historique_prix RESTART IDENTITY CASCADE;

TRUNCATE TABLE lot RESTART IDENTITY CASCADE;
TRUNCATE TABLE produit RESTART IDENTITY CASCADE;

TRUNCATE TABLE maladie RESTART IDENTITY CASCADE;
TRUNCATE TABLE symptome RESTART IDENTITY CASCADE;
TRUNCATE TABLE agentpathogene RESTART IDENTITY CASCADE;
TRUNCATE TABLE substance RESTART IDENTITY CASCADE;

TRUNCATE TABLE genre RESTART IDENTITY CASCADE;
TRUNCATE TABLE trancheage RESTART IDENTITY CASCADE;
TRUNCATE TABLE forme RESTART IDENTITY CASCADE;
TRUNCATE TABLE classe RESTART IDENTITY CASCADE;
TRUNCATE TABLE domaine RESTART IDENTITY CASCADE;
TRUNCATE TABLE typeproduit RESTART IDENTITY CASCADE;
TRUNCATE TABLE typesubstance RESTART IDENTITY CASCADE;
TRUNCATE TABLE typeagent RESTART IDENTITY CASCADE;

TRUNCATE TABLE laboratoire RESTART IDENTITY CASCADE;
TRUNCATE TABLE unite RESTART IDENTITY CASCADE;

TRUNCATE TABLE client RESTART IDENTITY CASCADE;
TRUNCATE TABLE fournisseur RESTART IDENTITY CASCADE;

-- Réactiver les contraintes de clé étrangère
SET session_replication_role = 'origin';

-- Vérifier que toutes les données ont été réinitialisées
SELECT 'Réinitialisation terminée' AS status;
